<?xml version="1.0"?>
<package format="3">
  <name>xesc</name>
  <version>1.0.0</version>
  <description>Metapackage of XESC packages.</description>

  <maintainer email="clemens1@familie-elflein.de">Clemens Elflein</maintainer>
  <author email="clemens1@familie-elflein.de">Clemens Elflein</author>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>xesc_msgs</exec_depend>
  <exec_depend>xesc_driver</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
