<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>mower_comms_v1</name>
  <version>0.0.0</version>
  <description>The mower_comms_v1 package - legacy serial COBS communication with low-level board</description>
  <maintainer email="clemens1@familie-elflein.de">Clemens Elflein</maintainer>
  <license>CC BY-NC-SA 4.0</license>

  <url type="website">https://github.com/ClemensElflein/OpenMower</url>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- ROS2 core -->
  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>std_msgs</depend>

  <!-- Custom message packages -->
  <depend>xbot_msgs</depend>
  <depend>mower_msgs</depend>
  <depend>xesc_msgs</depend>
  <depend>xesc_driver</depend>

  <!-- System dependencies -->
  <build_depend>libboost-dev</build_depend>
  <build_depend>libserial-dev</build_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
