<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>mower_logic</name>
  <version>0.0.0</version>
  <description>The mower_logic package</description>
  <maintainer email="clemens1@familie-elflein.de">Clemens Elflein</maintainer>
  <license>CC BY-NC-SA 4.0</license>

  <url type="website">https://github.com/ClemensElflein/OpenMower</url>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>rosidl_default_generators</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>rclcpp_action</depend>
  <depend>ftc_local_planner</depend>
  <depend>mbf_msgs</depend>
  <depend>mower_map</depend>
  <depend>mower_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>slic3r_coverage_planner</depend>
  <depend>tf2</depend>
  <depend>tf2_geometry_msgs</depend>
  <depend>tf2_ros</depend>
  <depend>tf2_eigen</depend>
  <depend>visualization_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>xbot_msgs</depend>
  <depend>xbot_positioning</depend>
  <depend>geometry_msgs</depend>
  <depend>std_msgs</depend>

  <build_depend>libcrypto++-dev</build_depend>
  <exec_depend>libcrypto++-dev</exec_depend>

  <exec_depend>joy</exec_depend>
  <exec_depend>imu_tools</exec_depend>
  <exec_depend>rosidl_default_runtime</exec_depend>

  <member_of_group>rosidl_interface_packages</member_of_group>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
