<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>xbot_remote</name>
  <version>0.0.0</version>
  <description>The xbot_remote package</description>
  <maintainer email="clemens.elflein@googlemail.com">Clemens Elflein</maintainer>
  <license>MIT</license>

  <url type="website">https://github.com/ClemensElflein</url>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclcpp</depend>
  <depend>xbot_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>std_msgs</depend>
  <build_depend>libwebsocketpp-dev</build_depend>
  <build_depend>nlohmann-json-dev</build_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
